/* QA V35.1 role-aware navigation. */
function htmlEscapeServer_(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function buildAppNavHtml_(baseUrl,activePage){
  const p=QA.profile||{}, role=p.role||'', isSystem=role==='system_admin', isDept=role==='department_admin';
  const links=[];
  const add=(page,label,icon,show=true)=>{if(!show)return;links.push('<a class="qa-side-link '+(activePage===page?'active':'')+'" href="'+htmlEscapeServer_(QA.pageUrl(page))+'"><span class="qa-side-icon">'+icon+'</span><span>'+label+'</span></a>');};
  add('work','ใบงาน','⌂');
  add('create','แจ้งงาน','＋',role!=='viewer');
  add('dashboard','Dashboard','▥',isDept||isSystem||role==='viewer');
  add('settings','Settings','⚙',isSystem);
  return `<style>
  :root{--qa-sidebar-width:236px;--qa-sidebar-bg:#111827;--qa-sidebar-border:#253047;--qa-sidebar-text:#dbe3ef;--qa-sidebar-muted:#8f9bad}
  .qa-app-content{margin-left:var(--qa-sidebar-width);min-height:100vh}.qa-sidebar{position:fixed;inset:0 auto 0 0;width:var(--qa-sidebar-width);background:#111827;color:#fff;z-index:9998;display:flex;flex-direction:column;border-right:1px solid var(--qa-sidebar-border)}
  .qa-side-brand{padding:14px;border-bottom:1px solid var(--qa-sidebar-border)}.qa-side-logo{height:54px;background:#fff;border-radius:9px;display:flex;align-items:center;overflow:hidden;margin-bottom:10px}.qa-side-logo img{width:100%;height:100%;object-fit:contain;object-position:left center}.qa-side-brand-title{font-size:15px;font-weight:800}.qa-side-brand-sub,.qa-side-footer{font-size:11px;color:var(--qa-sidebar-muted)}
  .qa-side-menu{padding:16px 12px;overflow:auto;flex:1}.qa-side-label{padding:0 10px 8px;font-size:11px;font-weight:700;color:var(--qa-sidebar-muted)}.qa-side-link{display:flex;align-items:center;gap:11px;padding:11px 12px;margin-bottom:5px;border-radius:9px;color:var(--qa-sidebar-text)!important;text-decoration:none!important;font-size:14px;font-weight:600}.qa-side-link:hover{background:#1f2937;color:#fff!important}.qa-side-link.active{background:#fff;color:#111827!important;font-weight:800}.qa-side-icon{width:28px;height:28px;border-radius:7px;display:flex;align-items:center;justify-content:center;background:#ffffff14}.qa-side-footer{padding:13px 18px 18px;border-top:1px solid var(--qa-sidebar-border);line-height:1.6}.qa-mobile-menu-btn{display:none;position:fixed;top:12px;left:12px;z-index:10001;width:42px;height:42px;border:0;border-radius:10px;background:#111827;color:#fff;font-size:22px}.qa-sidebar-overlay{display:none}
  @media(max-width:800px){.qa-app-content{margin-left:0;padding-top:58px}.qa-mobile-menu-btn{display:block}.qa-sidebar{transform:translateX(-102%);transition:.2s}.qa-sidebar.open{transform:none}.qa-sidebar-overlay{position:fixed;inset:0;background:#0f172a7a;z-index:9997}.qa-sidebar-overlay.show{display:block}}
  </style><button class="qa-mobile-menu-btn" type="button" onclick="toggleQaSidebar()">☰</button><div id="qaSidebarOverlay" class="qa-sidebar-overlay" onclick="closeQaSidebar()"></div><aside id="qaSidebar" class="qa-sidebar"><div class="qa-side-brand"><div class="qa-side-logo"><img src="labtech-logo.png" alt="LABTECH"></div><div class="qa-side-brand-title">Corrective Action</div><div class="qa-side-brand-sub">Inter-Department Work Request</div></div><nav class="qa-side-menu"><div class="qa-side-label">เมนูหลัก</div>${links.join('')}</nav><div class="qa-side-footer"><b>${htmlEscapeServer_(p.display_name||'')}</b><br>${htmlEscapeServer_(p.department||'-')} · ${htmlEscapeServer_(role.replaceAll('_',' '))}<br><span id="qa-release-version">V35.2 TEST</span><br><button type="button" onclick="QA.signOut()" style="margin-top:8px;padding:6px 10px;border:1px solid #475569;border-radius:6px;background:transparent;color:#dbe3ef;cursor:pointer">Sign out</button></div></aside>`;
}
window.toggleQaSidebar=function(){const s=document.getElementById('qaSidebar'),o=document.getElementById('qaSidebarOverlay');if(!s||!o)return;const open=s.classList.toggle('open');o.classList.toggle('show',open)};
window.closeQaSidebar=function(){document.getElementById('qaSidebar')?.classList.remove('open');document.getElementById('qaSidebarOverlay')?.classList.remove('show')};
window.mountQaNavigation=function(){if(document.getElementById('qaSidebar'))return;const page=QA.pageName();const wrap=document.createElement('div');wrap.innerHTML=buildAppNavHtml_('',page);const nodes=[...wrap.childNodes];for(const n of nodes)document.body.insertBefore(n,document.body.firstChild);const children=[...document.body.children].filter(el=>!el.matches('script,style,.qa-sidebar,.qa-mobile-menu-btn,.qa-sidebar-overlay')&&!el.classList.contains('qa-app-content'));if(children.length){const c=document.createElement('div');c.className='qa-app-content';document.body.insertBefore(c,children[0]);children.forEach(el=>c.appendChild(el));}};
